package org.man4fun.home.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.man4fun.home.model.OrderItem;
import org.man4fun.home.model.OrderItemExample;
import org.man4fun.home.model.OrderItemKey;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int deleteByPrimaryKey(OrderItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    OrderItem selectByPrimaryKey(OrderItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    int updateByPrimaryKey(OrderItem record);
}