package org.man4fun.home.model;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrder_numIsNull() {
            addCriterion("order_num is null");
            return (Criteria) this;
        }

        public Criteria andOrder_numIsNotNull() {
            addCriterion("order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_numEqualTo(Integer value) {
            addCriterion("order_num =", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numNotEqualTo(Integer value) {
            addCriterion("order_num <>", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numGreaterThan(Integer value) {
            addCriterion("order_num >", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_num >=", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numLessThan(Integer value) {
            addCriterion("order_num <", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numLessThanOrEqualTo(Integer value) {
            addCriterion("order_num <=", value, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numIn(List<Integer> values) {
            addCriterion("order_num in", values, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numNotIn(List<Integer> values) {
            addCriterion("order_num not in", values, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numBetween(Integer value1, Integer value2) {
            addCriterion("order_num between", value1, value2, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_numNotBetween(Integer value1, Integer value2) {
            addCriterion("order_num not between", value1, value2, "order_num");
            return (Criteria) this;
        }

        public Criteria andOrder_dateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrder_dateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_dateEqualTo(String value) {
            addCriterion("order_date =", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateNotEqualTo(String value) {
            addCriterion("order_date <>", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateGreaterThan(String value) {
            addCriterion("order_date >", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateGreaterThanOrEqualTo(String value) {
            addCriterion("order_date >=", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateLessThan(String value) {
            addCriterion("order_date <", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateLessThanOrEqualTo(String value) {
            addCriterion("order_date <=", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateLike(String value) {
            addCriterion("order_date like", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateNotLike(String value) {
            addCriterion("order_date not like", value, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateIn(List<String> values) {
            addCriterion("order_date in", values, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateNotIn(List<String> values) {
            addCriterion("order_date not in", values, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateBetween(String value1, String value2) {
            addCriterion("order_date between", value1, value2, "order_date");
            return (Criteria) this;
        }

        public Criteria andOrder_dateNotBetween(String value1, String value2) {
            addCriterion("order_date not between", value1, value2, "order_date");
            return (Criteria) this;
        }

        public Criteria andCust_idIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCust_idIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCust_idEqualTo(Integer value) {
            addCriterion("cust_id =", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idLessThan(Integer value) {
            addCriterion("cust_id <", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idIn(List<Integer> values) {
            addCriterion("cust_id in", values, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "cust_id");
            return (Criteria) this;
        }

        public Criteria andCust_idNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "cust_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}