package org.man4fun.home.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_num
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer order_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String order_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cust_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer cust_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_num
     *
     * @return the value of orders.order_num
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getOrder_num() {
        return order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_num
     *
     * @param order_num the value for orders.order_num
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrder_num(Integer order_num) {
        this.order_num = order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_date
     *
     * @return the value of orders.order_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getOrder_date() {
        return order_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_date
     *
     * @param order_date the value for orders.order_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrder_date(String order_date) {
        this.order_date = order_date == null ? null : order_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cust_id
     *
     * @return the value of orders.cust_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getCust_id() {
        return cust_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cust_id
     *
     * @param cust_id the value for orders.cust_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setCust_id(Integer cust_id) {
        this.cust_id = cust_id;
    }
}