package org.man4fun.home.model;

public class OrderItem extends OrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String prod_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.quantity
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.item_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Double item_price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.prod_id
     *
     * @return the value of orderitems.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getProd_id() {
        return prod_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.prod_id
     *
     * @param prod_id the value for orderitems.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_id(String prod_id) {
        this.prod_id = prod_id == null ? null : prod_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.quantity
     *
     * @return the value of orderitems.quantity
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.quantity
     *
     * @param quantity the value for orderitems.quantity
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.item_price
     *
     * @return the value of orderitems.item_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Double getItem_price() {
        return item_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.item_price
     *
     * @param item_price the value for orderitems.item_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setItem_price(Double item_price) {
        this.item_price = item_price;
    }
}