package org.man4fun.home.model;

import java.util.ArrayList;
import java.util.List;

public class ProductNoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public ProductNoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNote_idIsNull() {
            addCriterion("note_id is null");
            return (Criteria) this;
        }

        public Criteria andNote_idIsNotNull() {
            addCriterion("note_id is not null");
            return (Criteria) this;
        }

        public Criteria andNote_idEqualTo(Integer value) {
            addCriterion("note_id =", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idNotEqualTo(Integer value) {
            addCriterion("note_id <>", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idGreaterThan(Integer value) {
            addCriterion("note_id >", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("note_id >=", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idLessThan(Integer value) {
            addCriterion("note_id <", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idLessThanOrEqualTo(Integer value) {
            addCriterion("note_id <=", value, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idIn(List<Integer> values) {
            addCriterion("note_id in", values, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idNotIn(List<Integer> values) {
            addCriterion("note_id not in", values, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idBetween(Integer value1, Integer value2) {
            addCriterion("note_id between", value1, value2, "note_id");
            return (Criteria) this;
        }

        public Criteria andNote_idNotBetween(Integer value1, Integer value2) {
            addCriterion("note_id not between", value1, value2, "note_id");
            return (Criteria) this;
        }

        public Criteria andProd_idIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProd_idIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProd_idEqualTo(String value) {
            addCriterion("prod_id =", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotEqualTo(String value) {
            addCriterion("prod_id <>", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThan(String value) {
            addCriterion("prod_id >", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThanOrEqualTo(String value) {
            addCriterion("prod_id >=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThan(String value) {
            addCriterion("prod_id <", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThanOrEqualTo(String value) {
            addCriterion("prod_id <=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLike(String value) {
            addCriterion("prod_id like", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotLike(String value) {
            addCriterion("prod_id not like", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idIn(List<String> values) {
            addCriterion("prod_id in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotIn(List<String> values) {
            addCriterion("prod_id not in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idBetween(String value1, String value2) {
            addCriterion("prod_id between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotBetween(String value1, String value2) {
            addCriterion("prod_id not between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andNote_dateIsNull() {
            addCriterion("note_date is null");
            return (Criteria) this;
        }

        public Criteria andNote_dateIsNotNull() {
            addCriterion("note_date is not null");
            return (Criteria) this;
        }

        public Criteria andNote_dateEqualTo(String value) {
            addCriterion("note_date =", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateNotEqualTo(String value) {
            addCriterion("note_date <>", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateGreaterThan(String value) {
            addCriterion("note_date >", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateGreaterThanOrEqualTo(String value) {
            addCriterion("note_date >=", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateLessThan(String value) {
            addCriterion("note_date <", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateLessThanOrEqualTo(String value) {
            addCriterion("note_date <=", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateLike(String value) {
            addCriterion("note_date like", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateNotLike(String value) {
            addCriterion("note_date not like", value, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateIn(List<String> values) {
            addCriterion("note_date in", values, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateNotIn(List<String> values) {
            addCriterion("note_date not in", values, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateBetween(String value1, String value2) {
            addCriterion("note_date between", value1, value2, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_dateNotBetween(String value1, String value2) {
            addCriterion("note_date not between", value1, value2, "note_date");
            return (Criteria) this;
        }

        public Criteria andNote_textIsNull() {
            addCriterion("note_text is null");
            return (Criteria) this;
        }

        public Criteria andNote_textIsNotNull() {
            addCriterion("note_text is not null");
            return (Criteria) this;
        }

        public Criteria andNote_textEqualTo(String value) {
            addCriterion("note_text =", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textNotEqualTo(String value) {
            addCriterion("note_text <>", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textGreaterThan(String value) {
            addCriterion("note_text >", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textGreaterThanOrEqualTo(String value) {
            addCriterion("note_text >=", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textLessThan(String value) {
            addCriterion("note_text <", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textLessThanOrEqualTo(String value) {
            addCriterion("note_text <=", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textLike(String value) {
            addCriterion("note_text like", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textNotLike(String value) {
            addCriterion("note_text not like", value, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textIn(List<String> values) {
            addCriterion("note_text in", values, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textNotIn(List<String> values) {
            addCriterion("note_text not in", values, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textBetween(String value1, String value2) {
            addCriterion("note_text between", value1, value2, "note_text");
            return (Criteria) this;
        }

        public Criteria andNote_textNotBetween(String value1, String value2) {
            addCriterion("note_text not between", value1, value2, "note_text");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productnotes
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productnotes
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}