package org.man4fun.home.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String prod_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer vend_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.prod_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String prod_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.prod_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Double prod_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.prod_desc
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String prod_desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.prod_id
     *
     * @return the value of products.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getProd_id() {
        return prod_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.prod_id
     *
     * @param prod_id the value for products.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_id(String prod_id) {
        this.prod_id = prod_id == null ? null : prod_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.vend_id
     *
     * @return the value of products.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getVend_id() {
        return vend_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.vend_id
     *
     * @param vend_id the value for products.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_id(Integer vend_id) {
        this.vend_id = vend_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.prod_name
     *
     * @return the value of products.prod_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getProd_name() {
        return prod_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.prod_name
     *
     * @param prod_name the value for products.prod_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_name(String prod_name) {
        this.prod_name = prod_name == null ? null : prod_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.prod_price
     *
     * @return the value of products.prod_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Double getProd_price() {
        return prod_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.prod_price
     *
     * @param prod_price the value for products.prod_price
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_price(Double prod_price) {
        this.prod_price = prod_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.prod_desc
     *
     * @return the value of products.prod_desc
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getProd_desc() {
        return prod_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.prod_desc
     *
     * @param prod_desc the value for products.prod_desc
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_desc(String prod_desc) {
        this.prod_desc = prod_desc == null ? null : prod_desc.trim();
    }
}