package org.man4fun.home.model;

public class ProductNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productnotes.note_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer note_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productnotes.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String prod_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productnotes.note_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String note_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productnotes.note_text
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String note_text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productnotes.note_id
     *
     * @return the value of productnotes.note_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getNote_id() {
        return note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productnotes.note_id
     *
     * @param note_id the value for productnotes.note_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setNote_id(Integer note_id) {
        this.note_id = note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productnotes.prod_id
     *
     * @return the value of productnotes.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getProd_id() {
        return prod_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productnotes.prod_id
     *
     * @param prod_id the value for productnotes.prod_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setProd_id(String prod_id) {
        this.prod_id = prod_id == null ? null : prod_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productnotes.note_date
     *
     * @return the value of productnotes.note_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getNote_date() {
        return note_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productnotes.note_date
     *
     * @param note_date the value for productnotes.note_date
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setNote_date(String note_date) {
        this.note_date = note_date == null ? null : note_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productnotes.note_text
     *
     * @return the value of productnotes.note_text
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getNote_text() {
        return note_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productnotes.note_text
     *
     * @param note_text the value for productnotes.note_text
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setNote_text(String note_text) {
        this.note_text = note_text == null ? null : note_text.trim();
    }
}