package org.man4fun.home.model;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProd_idIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProd_idIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProd_idEqualTo(String value) {
            addCriterion("prod_id =", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotEqualTo(String value) {
            addCriterion("prod_id <>", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThan(String value) {
            addCriterion("prod_id >", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThanOrEqualTo(String value) {
            addCriterion("prod_id >=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThan(String value) {
            addCriterion("prod_id <", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThanOrEqualTo(String value) {
            addCriterion("prod_id <=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLike(String value) {
            addCriterion("prod_id like", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotLike(String value) {
            addCriterion("prod_id not like", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idIn(List<String> values) {
            addCriterion("prod_id in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotIn(List<String> values) {
            addCriterion("prod_id not in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idBetween(String value1, String value2) {
            addCriterion("prod_id between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotBetween(String value1, String value2) {
            addCriterion("prod_id not between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andVend_idIsNull() {
            addCriterion("vend_id is null");
            return (Criteria) this;
        }

        public Criteria andVend_idIsNotNull() {
            addCriterion("vend_id is not null");
            return (Criteria) this;
        }

        public Criteria andVend_idEqualTo(Integer value) {
            addCriterion("vend_id =", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotEqualTo(Integer value) {
            addCriterion("vend_id <>", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idGreaterThan(Integer value) {
            addCriterion("vend_id >", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("vend_id >=", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idLessThan(Integer value) {
            addCriterion("vend_id <", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idLessThanOrEqualTo(Integer value) {
            addCriterion("vend_id <=", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idIn(List<Integer> values) {
            addCriterion("vend_id in", values, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotIn(List<Integer> values) {
            addCriterion("vend_id not in", values, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idBetween(Integer value1, Integer value2) {
            addCriterion("vend_id between", value1, value2, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotBetween(Integer value1, Integer value2) {
            addCriterion("vend_id not between", value1, value2, "vend_id");
            return (Criteria) this;
        }

        public Criteria andProd_nameIsNull() {
            addCriterion("prod_name is null");
            return (Criteria) this;
        }

        public Criteria andProd_nameIsNotNull() {
            addCriterion("prod_name is not null");
            return (Criteria) this;
        }

        public Criteria andProd_nameEqualTo(String value) {
            addCriterion("prod_name =", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotEqualTo(String value) {
            addCriterion("prod_name <>", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameGreaterThan(String value) {
            addCriterion("prod_name >", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameGreaterThanOrEqualTo(String value) {
            addCriterion("prod_name >=", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLessThan(String value) {
            addCriterion("prod_name <", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLessThanOrEqualTo(String value) {
            addCriterion("prod_name <=", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLike(String value) {
            addCriterion("prod_name like", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotLike(String value) {
            addCriterion("prod_name not like", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameIn(List<String> values) {
            addCriterion("prod_name in", values, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotIn(List<String> values) {
            addCriterion("prod_name not in", values, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameBetween(String value1, String value2) {
            addCriterion("prod_name between", value1, value2, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotBetween(String value1, String value2) {
            addCriterion("prod_name not between", value1, value2, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_priceIsNull() {
            addCriterion("prod_price is null");
            return (Criteria) this;
        }

        public Criteria andProd_priceIsNotNull() {
            addCriterion("prod_price is not null");
            return (Criteria) this;
        }

        public Criteria andProd_priceEqualTo(Double value) {
            addCriterion("prod_price =", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotEqualTo(Double value) {
            addCriterion("prod_price <>", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceGreaterThan(Double value) {
            addCriterion("prod_price >", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceGreaterThanOrEqualTo(Double value) {
            addCriterion("prod_price >=", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceLessThan(Double value) {
            addCriterion("prod_price <", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceLessThanOrEqualTo(Double value) {
            addCriterion("prod_price <=", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceIn(List<Double> values) {
            addCriterion("prod_price in", values, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotIn(List<Double> values) {
            addCriterion("prod_price not in", values, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceBetween(Double value1, Double value2) {
            addCriterion("prod_price between", value1, value2, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotBetween(Double value1, Double value2) {
            addCriterion("prod_price not between", value1, value2, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_descIsNull() {
            addCriterion("prod_desc is null");
            return (Criteria) this;
        }

        public Criteria andProd_descIsNotNull() {
            addCriterion("prod_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProd_descEqualTo(String value) {
            addCriterion("prod_desc =", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descNotEqualTo(String value) {
            addCriterion("prod_desc <>", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descGreaterThan(String value) {
            addCriterion("prod_desc >", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descGreaterThanOrEqualTo(String value) {
            addCriterion("prod_desc >=", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descLessThan(String value) {
            addCriterion("prod_desc <", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descLessThanOrEqualTo(String value) {
            addCriterion("prod_desc <=", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descLike(String value) {
            addCriterion("prod_desc like", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descNotLike(String value) {
            addCriterion("prod_desc not like", value, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descIn(List<String> values) {
            addCriterion("prod_desc in", values, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descNotIn(List<String> values) {
            addCriterion("prod_desc not in", values, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descBetween(String value1, String value2) {
            addCriterion("prod_desc between", value1, value2, "prod_desc");
            return (Criteria) this;
        }

        public Criteria andProd_descNotBetween(String value1, String value2) {
            addCriterion("prod_desc not between", value1, value2, "prod_desc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table products
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table products
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}