package org.man4fun.home.model;

import java.util.ArrayList;
import java.util.List;

public class VendorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public VendorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVend_idIsNull() {
            addCriterion("vend_id is null");
            return (Criteria) this;
        }

        public Criteria andVend_idIsNotNull() {
            addCriterion("vend_id is not null");
            return (Criteria) this;
        }

        public Criteria andVend_idEqualTo(Integer value) {
            addCriterion("vend_id =", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotEqualTo(Integer value) {
            addCriterion("vend_id <>", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idGreaterThan(Integer value) {
            addCriterion("vend_id >", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("vend_id >=", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idLessThan(Integer value) {
            addCriterion("vend_id <", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idLessThanOrEqualTo(Integer value) {
            addCriterion("vend_id <=", value, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idIn(List<Integer> values) {
            addCriterion("vend_id in", values, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotIn(List<Integer> values) {
            addCriterion("vend_id not in", values, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idBetween(Integer value1, Integer value2) {
            addCriterion("vend_id between", value1, value2, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_idNotBetween(Integer value1, Integer value2) {
            addCriterion("vend_id not between", value1, value2, "vend_id");
            return (Criteria) this;
        }

        public Criteria andVend_nameIsNull() {
            addCriterion("vend_name is null");
            return (Criteria) this;
        }

        public Criteria andVend_nameIsNotNull() {
            addCriterion("vend_name is not null");
            return (Criteria) this;
        }

        public Criteria andVend_nameEqualTo(String value) {
            addCriterion("vend_name =", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameNotEqualTo(String value) {
            addCriterion("vend_name <>", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameGreaterThan(String value) {
            addCriterion("vend_name >", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameGreaterThanOrEqualTo(String value) {
            addCriterion("vend_name >=", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameLessThan(String value) {
            addCriterion("vend_name <", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameLessThanOrEqualTo(String value) {
            addCriterion("vend_name <=", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameLike(String value) {
            addCriterion("vend_name like", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameNotLike(String value) {
            addCriterion("vend_name not like", value, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameIn(List<String> values) {
            addCriterion("vend_name in", values, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameNotIn(List<String> values) {
            addCriterion("vend_name not in", values, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameBetween(String value1, String value2) {
            addCriterion("vend_name between", value1, value2, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_nameNotBetween(String value1, String value2) {
            addCriterion("vend_name not between", value1, value2, "vend_name");
            return (Criteria) this;
        }

        public Criteria andVend_addressIsNull() {
            addCriterion("vend_address is null");
            return (Criteria) this;
        }

        public Criteria andVend_addressIsNotNull() {
            addCriterion("vend_address is not null");
            return (Criteria) this;
        }

        public Criteria andVend_addressEqualTo(String value) {
            addCriterion("vend_address =", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressNotEqualTo(String value) {
            addCriterion("vend_address <>", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressGreaterThan(String value) {
            addCriterion("vend_address >", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressGreaterThanOrEqualTo(String value) {
            addCriterion("vend_address >=", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressLessThan(String value) {
            addCriterion("vend_address <", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressLessThanOrEqualTo(String value) {
            addCriterion("vend_address <=", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressLike(String value) {
            addCriterion("vend_address like", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressNotLike(String value) {
            addCriterion("vend_address not like", value, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressIn(List<String> values) {
            addCriterion("vend_address in", values, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressNotIn(List<String> values) {
            addCriterion("vend_address not in", values, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressBetween(String value1, String value2) {
            addCriterion("vend_address between", value1, value2, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_addressNotBetween(String value1, String value2) {
            addCriterion("vend_address not between", value1, value2, "vend_address");
            return (Criteria) this;
        }

        public Criteria andVend_cityIsNull() {
            addCriterion("vend_city is null");
            return (Criteria) this;
        }

        public Criteria andVend_cityIsNotNull() {
            addCriterion("vend_city is not null");
            return (Criteria) this;
        }

        public Criteria andVend_cityEqualTo(String value) {
            addCriterion("vend_city =", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityNotEqualTo(String value) {
            addCriterion("vend_city <>", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityGreaterThan(String value) {
            addCriterion("vend_city >", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityGreaterThanOrEqualTo(String value) {
            addCriterion("vend_city >=", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityLessThan(String value) {
            addCriterion("vend_city <", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityLessThanOrEqualTo(String value) {
            addCriterion("vend_city <=", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityLike(String value) {
            addCriterion("vend_city like", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityNotLike(String value) {
            addCriterion("vend_city not like", value, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityIn(List<String> values) {
            addCriterion("vend_city in", values, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityNotIn(List<String> values) {
            addCriterion("vend_city not in", values, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityBetween(String value1, String value2) {
            addCriterion("vend_city between", value1, value2, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_cityNotBetween(String value1, String value2) {
            addCriterion("vend_city not between", value1, value2, "vend_city");
            return (Criteria) this;
        }

        public Criteria andVend_stateIsNull() {
            addCriterion("vend_state is null");
            return (Criteria) this;
        }

        public Criteria andVend_stateIsNotNull() {
            addCriterion("vend_state is not null");
            return (Criteria) this;
        }

        public Criteria andVend_stateEqualTo(String value) {
            addCriterion("vend_state =", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateNotEqualTo(String value) {
            addCriterion("vend_state <>", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateGreaterThan(String value) {
            addCriterion("vend_state >", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateGreaterThanOrEqualTo(String value) {
            addCriterion("vend_state >=", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateLessThan(String value) {
            addCriterion("vend_state <", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateLessThanOrEqualTo(String value) {
            addCriterion("vend_state <=", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateLike(String value) {
            addCriterion("vend_state like", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateNotLike(String value) {
            addCriterion("vend_state not like", value, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateIn(List<String> values) {
            addCriterion("vend_state in", values, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateNotIn(List<String> values) {
            addCriterion("vend_state not in", values, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateBetween(String value1, String value2) {
            addCriterion("vend_state between", value1, value2, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_stateNotBetween(String value1, String value2) {
            addCriterion("vend_state not between", value1, value2, "vend_state");
            return (Criteria) this;
        }

        public Criteria andVend_zipIsNull() {
            addCriterion("vend_zip is null");
            return (Criteria) this;
        }

        public Criteria andVend_zipIsNotNull() {
            addCriterion("vend_zip is not null");
            return (Criteria) this;
        }

        public Criteria andVend_zipEqualTo(String value) {
            addCriterion("vend_zip =", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipNotEqualTo(String value) {
            addCriterion("vend_zip <>", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipGreaterThan(String value) {
            addCriterion("vend_zip >", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipGreaterThanOrEqualTo(String value) {
            addCriterion("vend_zip >=", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipLessThan(String value) {
            addCriterion("vend_zip <", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipLessThanOrEqualTo(String value) {
            addCriterion("vend_zip <=", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipLike(String value) {
            addCriterion("vend_zip like", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipNotLike(String value) {
            addCriterion("vend_zip not like", value, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipIn(List<String> values) {
            addCriterion("vend_zip in", values, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipNotIn(List<String> values) {
            addCriterion("vend_zip not in", values, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipBetween(String value1, String value2) {
            addCriterion("vend_zip between", value1, value2, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_zipNotBetween(String value1, String value2) {
            addCriterion("vend_zip not between", value1, value2, "vend_zip");
            return (Criteria) this;
        }

        public Criteria andVend_countryIsNull() {
            addCriterion("vend_country is null");
            return (Criteria) this;
        }

        public Criteria andVend_countryIsNotNull() {
            addCriterion("vend_country is not null");
            return (Criteria) this;
        }

        public Criteria andVend_countryEqualTo(String value) {
            addCriterion("vend_country =", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryNotEqualTo(String value) {
            addCriterion("vend_country <>", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryGreaterThan(String value) {
            addCriterion("vend_country >", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryGreaterThanOrEqualTo(String value) {
            addCriterion("vend_country >=", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryLessThan(String value) {
            addCriterion("vend_country <", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryLessThanOrEqualTo(String value) {
            addCriterion("vend_country <=", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryLike(String value) {
            addCriterion("vend_country like", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryNotLike(String value) {
            addCriterion("vend_country not like", value, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryIn(List<String> values) {
            addCriterion("vend_country in", values, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryNotIn(List<String> values) {
            addCriterion("vend_country not in", values, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryBetween(String value1, String value2) {
            addCriterion("vend_country between", value1, value2, "vend_country");
            return (Criteria) this;
        }

        public Criteria andVend_countryNotBetween(String value1, String value2) {
            addCriterion("vend_country not between", value1, value2, "vend_country");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vendors
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vendors
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}