package org.man4fun.home.model;

public class Vendor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private Integer vend_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_address
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_city
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_state
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_zip
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendors.vend_country
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    private String vend_country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_id
     *
     * @return the value of vendors.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public Integer getVend_id() {
        return vend_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_id
     *
     * @param vend_id the value for vendors.vend_id
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_id(Integer vend_id) {
        this.vend_id = vend_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_name
     *
     * @return the value of vendors.vend_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_name() {
        return vend_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_name
     *
     * @param vend_name the value for vendors.vend_name
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_name(String vend_name) {
        this.vend_name = vend_name == null ? null : vend_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_address
     *
     * @return the value of vendors.vend_address
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_address() {
        return vend_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_address
     *
     * @param vend_address the value for vendors.vend_address
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_address(String vend_address) {
        this.vend_address = vend_address == null ? null : vend_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_city
     *
     * @return the value of vendors.vend_city
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_city() {
        return vend_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_city
     *
     * @param vend_city the value for vendors.vend_city
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_city(String vend_city) {
        this.vend_city = vend_city == null ? null : vend_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_state
     *
     * @return the value of vendors.vend_state
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_state() {
        return vend_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_state
     *
     * @param vend_state the value for vendors.vend_state
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_state(String vend_state) {
        this.vend_state = vend_state == null ? null : vend_state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_zip
     *
     * @return the value of vendors.vend_zip
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_zip() {
        return vend_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_zip
     *
     * @param vend_zip the value for vendors.vend_zip
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_zip(String vend_zip) {
        this.vend_zip = vend_zip == null ? null : vend_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendors.vend_country
     *
     * @return the value of vendors.vend_country
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public String getVend_country() {
        return vend_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendors.vend_country
     *
     * @param vend_country the value for vendors.vend_country
     *
     * @mbg.generated Thu Jan 11 11:52:50 CST 2018
     */
    public void setVend_country(String vend_country) {
        this.vend_country = vend_country == null ? null : vend_country.trim();
    }
}